name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들을 불러오기
        uses: actions/checkout@v5.0.0

      - name: JDK 21버전 설치
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: application.yaml 파일 만들기
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yaml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build -x test

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./soundscape.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: soundscape.jar
          target: /home/ec2-user/soundscape/tobe

      - name: SSH로 EC2에 접속
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ec2-user/soundscape/current
            mkdir /home/ec2-user/soundscape/current
            mv /home/ec2-user/soundscape/tobe/soundscape.jar /home/ec2-user/soundscape/current/soundscape.jar
            cd /home/ec2-user/soundscape/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar soundscape.jar > ./output.log 2>&1 &
            rm -rf /home/ec2-user/soundscape/tobe
